name: releaser
on: 
  push:
    tags:
    - 'v*'
  workflow_dispatch:
jobs:
    goreleaser:
        name: run goreleaser 🔧 
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: Set up Go
                uses: actions/setup-go@v5
                with:
                    go-version: stable

            -   name: Run GoReleaser
                uses: goreleaser/goreleaser-action@v6
                with:
                    # either 'goreleaser' (default) or 'goreleaser-pro'
                    distribution: goreleaser
                    args: release --clean 
                    # 'latest', 'nightly', or a semver
                    version: ~> v2
                env:
                    INTERROGATOR_VERSION: ${{ github.ref_name }}
                    GITHUB_TOKEN: ${{ secrets.GORELEASER_TOKEN }}